travis:
  secure:
    BINSTAR_TOKEN: H78UEaJANvbUhRGitclO/oW78uB8u0q+y3szkGPz3KIjlnzMI7ZIG75kHlNpGD4pKYvrbRIp77yqBrNbvKoQz5PBNtpsrlgnqsqT0K6ZI9/C/XYeqAXnXZQN4EB0o8VgOiB9V0R+m8cZjinXkUmS9eVDHJ5/+adpbk9itaR5UckICGwuVCvIRsvSC6/rouO3y1Gd9Igu7V7Z6NLPAwHtNoBD+ooaaXflYymitQt7xWg2Xxcw56xkBVDXj0SlqWW4NLVg/mfmp6A6G3HGzE81WbDoBVtfIe7dzVJF93LbpXe0IhpOW2iV2wzhKiyJCP+Ra5ihU3bbkEuumFzM2aV12LkuaizKYq7LNvYBtLf04ThFFXI6vQKONIEKe6RKbbaaCeYOJoxbQS6lsP7Fgd2eWRAAY/rYUvUFebE6/dYkPrqSAf9dE6XQi2wV96sHpv19KaI6g2HeDTBiS8p2U6owLGDEtZfGcrYx64mN8DZWlJZXclspYTAG4n4U8oI3VqjSiKxZKaL4TGTkhCgsNEACDVD19O1O2uROWk5A9uTlFcAoQ8+hcKaWwH1d0fX1P/56pxErBvPrY29Aqw7qqLSxrZjsdT2SzSm2uYvRKNahmwBywIuoURWmdKpAAyMuHrIQN6C7whNejNuYyO+lxuzKboYooZZVzCc5JgZc2Frogmo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
